
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest_with_spring-boot?useTimezone=true&serverTimezone=UTC
    usename:root
    password:admin123
    jpa:
    hibernate